name: Build and optional release
on: [push]

jobs:
  publish:
    name: Build and publish aar library
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '17'

      - name: Build AAR
        run: ./gradlew assemble

      - name: Archive .aar as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: aar lib
          path: |
            build/outputs/aar/nabto-api-release.aar

      - name: Release aar # on if the build is from a tag
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            build/outputs/aar/nabto-api-release.aar
